package Input

import (
	"fmt"
)

/*
DispatchKeyEventParams represents Input.dispatchKeyEvent parameters.
*/
type DispatchKeyEventParams struct {
	// Type of the key event. Allowed values: keyDown, keyUp, rawKeyDown, char.
	Type string `json:"type"`

	// Optional. Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4,
	// Shift=8 (default: 0).
	Modifiers int `json:"modifiers,omitempty"`

	// Optional. Time at which the event occurred.
	Timestamp TimeSinceEpoch `json:"timestamp,omitempty"`

	// Optional. Text as generated by processing a virtual key code with a keyboard layout. Not
	// needed for for `keyUp` and `rawKeyDown` events (default: "").
	Text string `json:"text,omitempty"`

	// Optional. Text that would have been generated by the keyboard if no modifiers were pressed
	// (except for shift). Useful for shortcut (accelerator) key handling (default: "").
	UnmodifiedText string `json:"unmodifiedText,omitempty"`

	// Optional. Unique key identifier (e.g., 'U+0041') (default: "").
	KeyIdentifier string `json:"keyIdentifier,omitempty"`

	// Optional. Unique DOM defined string value for each physical key (e.g., 'KeyA') (default: "").
	Code string `json:"code,omitempty"`

	// Optional. Unique DOM defined string value describing the meaning of the key in the context of
	// active modifiers, keyboard layout, etc (e.g., 'AltGr') (default: "").
	Key string `json:"key,omitempty"`

	// Optional. Windows virtual key code (default: 0).
	WindowsVirtualKeyCode int `json:"windowsVirtualKeyCode,omitempty"`

	// Optional. Native virtual key code (default: 0).
	NativeVirtualKeyCode int `json:"nativeVirtualKeyCode,omitempty"`

	// Optional. Whether the event was generated from auto repeat (default: false).
	AutoRepeat bool `json:"autoRepeat,omitempty"`

	// Optional. Whether the event was generated from the keypad (default: false).
	IsKeypad bool `json:"isKeypad,omitempty"`

	// Optional. Whether the event was a system key event (default: false).
	IsSystemKey bool `json:"isSystemKey,omitempty"`

	// Optional. Whether the event was from the left or right side of the keyboard. 1=Left, 2=Right
	// (default: 0).
	Location int `json:"location,omitempty"`
}

/*
DispatchMouseEventParams represents Input.dispatchMouseEvent parameters.
*/
type DispatchMouseEventParams struct {
	// Type of the mouse event. Allowed values: mousePressed, mouseReleased, mouseMoved, mouseWheel.
	Type string `json:"type"`

	// X coordinate of the event relative to the main frame's viewport in CSS pixels.
	X int `json:"x"`

	// Y coordinate of the event relative to the main frame's viewport in CSS pixels. 0 refers to
	// the top of the viewport and Y increases as it proceeds towards the bottom of the viewport.
	Y int `json:"y"`

	// Optional. Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4,
	// Shift=8 (default: 0).
	Modifiers int `json:"modifiers,omitempty"`

	// Optional. Time at which the event occurred.
	Timestamp TimeSinceEpoch `json:"timestamp,omitempty"`

	// Optional. Mouse button (default: "none"). Allowed values: none, left, middle, right.
	Button string `json:"button,omitempty"`

	// Optional. Number of times the mouse button was clicked (default: 0).
	ClickCount int `json:"clickCount,omitempty"`

	// Optional. X delta in CSS pixels for mouse wheel event (default: 0).
	DeltaX int `json:"deltaX,omitempty"`

	// Optional. Y delta in CSS pixels for mouse wheel event (default: 0).
	DeltaY int `json:"deltaY,omitempty"`
}

/*
DispatchTouchEventParams represents Input.dispatchTouchEvent parameters.
*/
type DispatchTouchEventParams struct {
	// Type of the touch event. TouchEnd and TouchCancel must not contain any touch points, while
	// TouchStart and TouchMove must contains at least one. Allowed values: touchStart, touchEnd,
	// touchMove, touchCancel.
	Type string `json:"type"`

	// Active touch points on the touch device. One event per any changed point (compared to
	// previous touch event in a sequence) is generated, emulating pressing/moving/releasing points
	// one by one.
	TouchPoints []*TouchPoint `json:"touchPoints"`

	// Optional. Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4,
	// Shift=8 (default: 0).
	Modifiers int `json:"modifiers,omitempty"`

	// Optional. Time at which the event occurred.
	Timestamp TimeSinceEpoch `json:"timestamp,omitempty"`
}

/*
EmulateTouchFromMouseEventParams represents Input.emulateTouchFromMouseEvent parameters.
*/
type EmulateTouchFromMouseEventParams struct {
	// Type of the mouse event. Allowed values: mousePressed, mouseReleased, mouseMoved, mouseWheel.
	Type string `json:"type"`

	// X coordinate of the mouse pointer in DIP.
	X int `json:"x"`

	// Y coordinate of the mouse pointer in DIP.
	Y int `json:"y"`

	// Time at which the event occurred.
	Timestamp TimeSinceEpoch `json:"timestamp"`

	// Mouse button. Allowed values: none, left, middle, right.
	Button string `json:"button"`

	// Optional. X delta in DIP for mouse wheel event (default: 0).
	DeltaX int `json:"deltaX,omitempty"`

	// Optional. Y delta in DIP for mouse wheel event (default: 0).
	DeltaY int `json:"deltaY,omitempty"`

	// Optional. Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4,
	// Shift=8 (default: 0).
	Modifiers int `json:"modifiers,omitempty"`

	// Optional. Number of times the mouse button was clicked (default: 0).
	ClickCount int `json:"clickCount,omitempty"`
}

/*
SetIgnoreInputEventsParams represents Input.setIgnoreInputEvents parameters.
*/
type SetIgnoreInputEventsParams struct {
	// Ignores input events processing when set to true.
	Ignore bool `json:"ignore"`
}

/*
SynthesizePinchGestureParams represents Input.synthesizePinchGesture parameters.
*/
type SynthesizePinchGestureParams struct {
	// X coordinate of the start of the gesture in CSS pixels.
	X float64 `json:"x"`

	// Y coordinate of the start of the gesture in CSS pixels.
	Y float64 `json:"y"`

	// Relative scale factor after zooming (>1.0 zooms in, <1.0 zooms out).
	ScaleFactor int `json:"scaleFactor"`

	// Optional. Relative pointer speed in pixels per second (default: 800).
	RelativeSpeed int `json:"relativeSpeed,omitempty"`

	// Optional. Which type of input events to be generated (default: 'default', which queries the
	// platform for the preferred input type).
	GestureSourceType GestureSourceType `json:"gestureSourceType,omitempty"`
}

/*
SynthesizeScrollGestureParams represents Input.synthesizeScrollGesture parameters.
*/
type SynthesizeScrollGestureParams struct {
	// X coordinate of the start of the gesture in CSS pixels.
	X int `json:"x"`

	// Y coordinate of the start of the gesture in CSS pixels.
	Y int `json:"y"`

	// Optional. The distance to scroll along the X axis (positive to scroll left).
	XDistance int `json:"xDistance,omitempty"`

	// Optional. The distance to scroll along the Y axis (positive to scroll up).
	YDistance int `json:"yDistance,omitempty"`

	// Optional. The number of additional pixels to scroll back along the X axis, in addition to the
	// given distance.
	XOverscroll int `json:"xOverscroll,omitempty"`

	// Optional. The number of additional pixels to scroll back along the Y axis, in addition to the
	// given distance.
	YOverscroll int `json:"yOverscroll,omitempty"`

	// Optional. Prevent fling (default: true).
	PreventFling bool `json:"preventFling,omitempty"`

	// Optional. Swipe speed in pixels per second (default: 800).
	Speed int `json:"speed,omitempty"`

	// Optional. Which type of input events to be generated (default: 'default', which queries the
	// platform for the preferred input type).
	GestureSourceType GestureSourceType `json:"gestureSourceType,omitempty"`

	// Optional. The number of times to repeat the gesture (default: 0).
	RepeatCount int `json:"repeatCount,omitempty"`

	// Optional. The number of milliseconds delay between each repeat. (default: 250).
	RepeatDelayMs int `json:"repeatDelayMs,omitempty"`

	// Optional. The name of the interaction markers to generate, if not empty (default: "").
	InteractionMarkerName string `json:"interactionMarkerName,omitempty"`
}

/*
SynthesizeTapGestureParams represents Input.synthesizeTapGesture parameters.
*/
type SynthesizeTapGestureParams struct {
	// X coordinate of the start of the gesture in CSS pixels.
	X int `json:"x"`

	// Y coordinate of the start of the gesture in CSS pixels.
	Y int `json:"y"`

	// Optional. Duration between touchdown and touchup events in ms (default: 50).
	Duration int `json:"duration,omitempty"`

	// Optional. Number of times to perform the tap (e.g. 2 for double tap, default: 1).
	TapCount int `json:"tapCount,omitempty"`

	// Optional. Which type of input events to be generated (default: 'default', which queries the
	// platform for the preferred input type).
	GestureSourceType GestureSourceType `json:"gestureSourceType,omitempty"`
}

/*
TouchPoint is a touch point.
*/
type TouchPoint struct {
	// X coordinate of the event relative to the main frame's viewport in CSS pixels.
	X int `json:"x"`

	// Y coordinate of the event relative to the main frame's viewport in CSS pixels. 0 refers to
	// the top of the viewport and Y increases as it proceeds towards the bottom of the viewport.
	Y int `json:"y"`

	// Optional. X radius of the touch area (default: 1.0).
	RadiusX int `json:"radiusX,omitempty"`

	// Optional. Y radius of the touch area (default: 1.0).
	RadiusY int `json:"radiusY,omitempty"`

	// Optional. Rotation angle (default: 0.0).
	RotationAngle int `json:"rotationAngle,omitempty"`

	// Optional. Force (default: 1.0).
	Force int `json:"force,omitempty"`

	// Optional. Identifier used to track touch sources between events, must be unique within an
	// event.
	ID int `json:"id,omitempty"`
}

/*
GestureSourceType is a gesture source type. EXPERIMENTAL
*/
type GestureSourceType int

const (
	_default GestureSourceType = iota
	_touch
	_mouse
)

func (a GestureSourceType) String() string {
	if a == 0 {
		return "default"
	}
	if a == 1 {
		return "touch"
	}
	if a == 2 {
		return "mouse"
	}
	panic(fmt.Errorf("Invalid GestureSourceType %d", a))
}

/*
TimeSinceEpoch is UTC time in seconds, counted from January 1, 1970.
*/
type TimeSinceEpoch int
