notifications:
    slack:
        secure: fWCW6/ntsoE+MFGPcsaXvif/GpQEbWl1zDm5rT41b17X4Ac+Zlm0LbV8m7MqX1XF/T3jSkZolBx3+CDfORuT0UqFTd/bEYc2/gScPE04gmV38fhOPhQYTTHegpM7vlQf8yJ579fz72If55jER1hCLLPEgelPC8CbTaVfrawBVl2VO2AStOLGRLjBiNvbIVzzvEP9rbuksKcjzgO0PU5vdBgIxN9zpltNtEuq/x/3a/KGxdWfXarMNrC1MxEMNzdJkYtrdYewHfGKEl+bMxDLF1nbgbA7DortV6Me1qVic9hLBgfyjKqyT7Q53cl0JQNTongcz7nn8UglsABSEpVHrIIBA9LclWRbiFNvfrsNKoSqpnVlujsJsWZPK0aSZnFGWJlYpA+X6EuqxEXbcDnqOBeplKDhPa21amwC1Cli8Vsw7H0hq+Wf2zIcQG60qumy8yN+nweT0OC9L0NfZuCn0Xr2hb6qbjU3Xr1gpt60+JZYd8I69L0Iibhh+ZYX1yQzi+s51p5KKfr5QjitFQsZ/5Z9t+Mpca36uqt3EYG+RDmtvik0IbV3l2xEMMp4XzT3Xqe/Vh8aKc2rrYWtF2In1aqJd2z7iCOvA8ehuDj2vBc0uDl67YIWnRZ167N+IxPF1B3yXC8lNms+FZ3tg2/C4dAwT9TyWXyr0K02o3M6sX4=

git:
    depth: 1
    quiet: true
    submodules: false

branches:
    only:
        - master

services:
    - docker

language: go
go_import_path: github.com/mkenney/go-chrome
go:
    - 1.9.x
    - 1.10.x
    - tip


script:
    - ./.travis.sh
after_success:
    - bash <(curl -s https://codecov.io/bash)
