[[constraint]]
  branch = "master"
  name = "github.com/mkenney/go-log-fmt"

[[constraint]]
  branch = "master"
  name = "github.com/mkenney/go-errors"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"
